apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-projectmanagement-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi