FROM node:18-alpine
WORKDIR /app
COPY . .
RUN npm install snyk -g
RUN npm install snyk-to-html -g

ARG SNYK_AUTH_TOKEN
ENV SNYK_AUTH_TOKEN=$SNYK_AUTH_TOKEN

ARG SNYK_OUTPUT_FILE_REPORT
ENV SNYK_OUTPUT_FILE_REPORT=$SNYK_OUTPUT_FILE_REPORT

RUN snyk auth $SNYK_AUTH_TOKEN && snyk tets --json | snyk-to-html -o $SNYK_OUTPUT_FILE_REPORT.html || true