apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - "./infras/k8s_test/*"
build:
  local:
    push: false
  artifacts:
    - image: longle2003/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/comment
      context: comment
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/issue
      context: Issue
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/projectmanagement
      context: Projectmanagement
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/category
      context: category
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'