apiVersion: skaffold/v4beta5
kind: Config
manifests:
  rawYaml:
    - "./infras/k8s_test/test/*"
build:
  local:
    push: false
  artifacts:
    - image: longle2003/auth
      context: auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
          - src: "src/**/*.css"
            dest: .
    - image: longle2003/comment
      context: comment
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/issue
      context: issue
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/projectmanagement
      context: project_management
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/category
      context: category
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/sprint
      context: sprint
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/issue_history
      context: issue_history
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'
    - image: longle2003/issue_process
      context: issue_process
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - dest: .
            src: 'src/**/*.js'