# global:
#   resolve_timeout: 5m
# route: 
#   groupBy: ['severity']
#   groupWait: 30s
#   groupInterval: 5m
#   repeatInterval: 12h
#   receiver: 'email'
# receivers:
#   - name: 'email'
#     email_configs:
#       - to: 'ltphilong2001@gmail.com'
#         from: 'ltphilong2001@gmail.com'
#         smarthost: 'smtp.gmail.com:587'
#         auth_username: 'ltphilong2001@gmail.com'
#         auth_identity: 'ltphilong2001@gmail.com'
#         auth_password:
global:
  resolve_timeout: 5m
route:
  receiver: 'email-alert'
  group_by: ['severity']

  routes:
  - receiver: 'email-alert'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h  

receivers:
- name: email-alert
  email_configs:
  - to: ltphilong2001@gmail.com
    from: ltphilong2001@gmail.com
    # Your smtp server address
    smarthost: smtp.gmail.com:587
    auth_username: ltphilong2001@gmail.com
    auth_identity: ltphilong2001@gmail.com
    auth_password: lbswcqubtruhtqah