apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-issueprocess
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: issueprocess-depl
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60