apiVersion: apps/v1
kind: Deployment
metadata: 
  name: category-mongo-depl
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: category-mongo
  template: 
    metadata:
      labels: 
        app: category-mongo
    spec: 
      containers: 
        - name: db
          image: mongo
          volumeMounts:
            - name: category-persistent-storage
              mountPath: /data/db
      volumes:
        - name: category-persistent-storage
          persistentVolumeClaim:
            claimName: ebs-category-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: category-mongo-srv
spec:
  selector: 
    app: category-mongo
  ports:  
    - name: category-db
      protocol: TCP
      port: 27017
      targetPort: 27017
