apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-depl
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: issue
  template:
    metadata:   
      labels: 
        app: issue
    spec:
      imagePullSecrets:
        - name: authenticate-registry
      hostAliases:
        - ip: "192.168.73.101"
          hostnames:
          - "gitlab.taskscheduler.com"
      containers:
        - name: issue
          image: longle2003/issue
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "jiraproject"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URL
              value: "mongodb://issue-mongo-srv:27017/issues"
---
apiVersion: v1
kind: Service
metadata:
  name: issue-nodeport-srv
spec: 
  type: NodePort
  selector: 
    app: issue
  ports:
    - name: issue
      protocol: TCP
      port: 4002
      targetPort: 4002