apiVersion: apps/v1
kind: Deployment
metadata: 
  name: category-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category
  template:
    metadata:
      labels:
        app: category
    spec:
      containers:
        - name: category
          image: longle2003/category:latest
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_key
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: "jiraproject"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URL
              value: "mongodb://category-mongo-srv:27017/categories"
---

apiVersion: v1
kind: Service
metadata:
  name: category-nodeport-srv
spec: 
  type: NodePort
  selector:
    app: category
  ports:
    - name: category
      protocol: TCP
      port: 4004
      targetPort: 4004