apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-ssl
  namespace: default
spec:
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: ca-ingress-ssl
  dnsNames:
  - www.khoaluantotnghiep.click