apiVersion: v1
kind: Service
metadata:
  name: client-classic-loadbalancer-srv
  labels: 
    app: client
spec: 
  type: LoadBalancer 
  selector:
    app: client
  ports:
    - name: client
      port: 3000
      targetPort: 3000