apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: client-depl
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause: {}
      - setWeight: 40
      - pause: { duration: 10s }
      - setWeight: 60
      - pause: { duration: 10s }
      - pause: {}
      - setWeight: 80
      - pause: { duration: 10s }
      - setWeight: 100
      
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: longle2003/client:1111
        ports:
        - name: http
          containerPort: 3006
          protocol: TCP
        resources:
            requests:
              memory: "250Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
    name: client
  selector:
    app: client