apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl-1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: client-1
  template:
    metadata:
      labels:
        app: client-1
    spec:
      containers:
        - name: client-1
          image: longle2003/client:v10.1

---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  type: NodePort
  selector:
    app: client-1
  ports:
    - name: client-1
      protocol: TCP
      port: 3006
      targetPort: 3006
