apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-kong-pvc
  namespace: kong
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 3Gi