name: test-issue

on:
  pull_request:
    paths:
      - "Issue/**"

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd Issue && npm install && npm run test:ci
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: Issue/
          args: >
            -Dsonar.organization=longle11
            -Dsonar.projectKey=longle11_NT114.O21.MMCL-DACN-MICROSERVICE
            -Dsonar.sources=./Issue