name: test-issue

on:
  push:
    branches:
      - pull_request
    paths:
      - "Issue/**"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cd Issue && npm install && npm run test:ci