name: test-comment

on:
  push:
    branches:
      - pull_request"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cd comment && npm install && npm run test:ci