name: test-projectmanagement

on:
  pull_request:
    types: [opened, synchronize, edited, ready_for_review]
    paths: 
      - "ProjectManagement/**"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd ProjectManagement && npm install && npm run test:coverage
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ProjectManagement/