name: test-auth

on:
  push:
    branches:
      - pull_request
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cd auth && npm install && npm run test:ci