name: test-comment

on:
  pull_request:
    paths:
      - "comment/**"
jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd comment && npm install && npm run test:ci